apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-counter-backend
  labels:
    name: visitor-counter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visitor-counter-backend
  template:
    metadata:
      labels:
        app: visitor-counter-backend
    spec:
      containers:
      - name: visitor-counter-backend
        image: kartikd007/visitor-counter-backend:v1
        imagePullPolicy: Always
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        ports:
        - name: backend-port
          containerPort: 5000
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: visitor-counter-backend
spec:
  selector:
    app: visitor-counter-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
